dist: xenial
language: python
services:
  - xvfb
python:
  - "3.6"

env:
  # Will kick of 2 builds. One for units and one for tasks.
  - TEST_DIR=unit
  - TEST_DIR=demos
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
install:
  - cd ../
  - cur=`pwd`
  # Pull V-REP
  - wget http://www.coppeliarobotics.com/files/CoppeliaSim_Edu_V4_1_0_Ubuntu16_04.tar.xz
  - tar -xf CoppeliaSim_Edu_V4_1_0_Ubuntu16_04.tar.xz
  - export COPPELIASIM_ROOT="$cur/CoppeliaSim_Edu_V4_1_0_Ubuntu16_04"
  - echo $COPPELIASIM_ROOT
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COPPELIASIM_ROOT:$COPPELIASIM_ROOT/platforms
  - export QT_QPA_PLATFORM_PLUGIN_PATH=$COPPELIASIM_ROOT

  # Install PyRep
  - git clone https://github.com/stepjam/PyRep.git
  - cd PyRep
  - pip3 install ".[dev]"

  # Gym needed for some of unit tests
  - pip3 install gym

  # Go back to RLBench repo
  - cd ../RLBench
  - pip3 install ".[dev]"
# command to run tests
script:
  # Runs unit tests and generates reports (110  min timeout)
  - travis_wait 110 python3 travisci_run_tests.py $TEST_DIR $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER
after_script:
  # Get previously generated index file
  - git clone --quiet --branch=gh-pages https://${GITHUB_TOKEN}@github.com/stepjam/RLBench.git gh-pages
  - cd gh-pages

  # Generated html files will be one directory above
  - cp -r ../reports .
  # Move script that will amend the index
  - mv ../travisci_generate_index.py .

  # Generated new index.html
  - python3 travisci_generate_index.py $TEST_DIR $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER $TRAVIS_TEST_RESULT

  # Push generate html to gh-pages branch
  - git add index.html reports/
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
  - git push -fq origin gh-pages
