name: Task Tests

# Controls when the action will run.
# Run this workflow every time a new commit pushed to your repository
on:
  # Triggers the workflow on push or pull request events.
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      DISPLAY: :0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y xvfb qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev qt5-default qttools5-dev-tools
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
          cur=`pwd`
          wget https://downloads.coppeliarobotics.com/V4_1_0/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04.tar.xz
          tar -xf CoppeliaSim_Edu_V4_1_0_Ubuntu20_04.tar.xz
          export COPPELIASIM_ROOT="$cur/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04"
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COPPELIASIM_ROOT:$COPPELIASIM_ROOT/platforms
          export QT_QPA_PLATFORM_PLUGIN_PATH=$COPPELIASIM_ROOT

          pip install ".[gym,dev]"
          pip install "pytest-xdist[psutil]"
          pytest -v -n auto tests/demos
